# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Google analytics code, get your code here https://www.google.com/analytics/
google_analytics:   UA-143424917-13

gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-avatar
  - jekyll-redirect-from
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules

include: 
  - ".well-known"
